### ISSUE TITLE
Doesn't group

### ISSUE THREAD

**Issue by creold** [Inventsable/Frame-Inside#1]
Hi, Tom. Saw your new script and tried it. But there's no result. 🤔

![2022-05-24 09 37 49](https://user-images.githubusercontent.com/32217031/169950387-a23ab82f-23ee-4de8-bcb6-e00b8511c51b.gif)

**Comment by Inventsable** [comment]
Hi Sergey, only have the one named Test selected. This was by request from a certain user who had a particular need with hundreds of pageitems, so I didn't go too deeply into documenting things.

**Comment by creold** [comment]
Yes, it worked. Thank you
